"""Tiny Color·Gray wafer on disk for tests (real JPEGs made once with Chromium's canvas —
the project has no Pillow)."""
import base64
from pathlib import Path

COLOR_JPEG = base64.b64decode("/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAiAC4DASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAcFBv/EACYQAAEDAwEIAwAAAAAAAAAAAAABAgQFBhIRAxMWITZRgrJUo9H/xAAXAQADAQAAAAAAAAAAAAAAAAAABQYE/8QAJhEAAQMCBQQDAQAAAAAAAAAAAQADEQIEBRITMVEGIUGBFBUyYf/aAAwDAQACEQMRAD8A3ACWXr1NM8PRpPYXh32DxazZYE7T5A5HKoL+8+G2HMsyY3jlVMEQNyyupofn6OHFx0xoM1u6s5QT+eBPKWs47quUt6cSQN+fSqYAJVUCHA3Rb9TnV2TIixs9i/HF28amujUReSr3Q74G2wv3LBwutAEkR39f0cLLd2lF3QKKyYmeylnCla+H9rP01bXt+pwa7GkSo2GxZlk7eNXTVqonJF7qd8Bk91JdPN1NVU0xUCNj59rC1grDVYrBMgz48ekAAgThAACEAAIQAAhf/9k=")
GRAY_JPEG = base64.b64decode("/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAfAGADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQgJ/8QAFhAAAwAAAAAAAAAAAAAAAAAAAARB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AJ3UgypAZSDKkAYVgypAZWDKkAZUgwpAdSDCkAZUgwpAdSDCkAZUgwrAdSDCsAZUgwpAdSDCkAzxUgypAZSDKkAYVgypAZWDKkAZUgwpAZSDKkAZUgwpAdSDCkAZUgwrAdSDCsAZUgwpAdSDCkA//9k=")


def make_wafer(folder, name="W01"):
    """One wafer: 3 color images — C1 matches two frames (F1 wins, farther from the edge),
    C2 matches none, C3 names a missing color file."""
    w = Path(folder) / name
    w.mkdir(parents=True, exist_ok=True)
    (w / "C1.jpg").write_bytes(COLOR_JPEG)
    (w / "F1.t.1.jpg").write_bytes(GRAY_JPEG)
    (w / "F2.t.1.jpg").write_bytes(GRAY_JPEG)
    (w / "ColorImageGrabingInfo.ini").write_text(
        "[C1.jpg]\nFaultX=1100\nFaultY=200\nRecipeNumber=1\nImageSizeX=46\nImageSizeY=34\n"
        "PixelSizeX=0.4674\nPixelSizeY=0.4674\n"
        "[C2.jpg]\nFaultX=90000\nFaultY=90000\nRecipeNumber=1\n"
        "[C3.jpg]\nFaultX=1100\nFaultY=210\nRecipeNumber=1\n", encoding="utf-8")
    (w / "ScanResultImageList.txt").write_text("Version=1\nF1.t.1.jpg,0,0\nF2.t.1.jpg,1000,0\n", encoding="utf-8")
    (w / "frameToChuckPlane.1.ini").write_text("Scan_X=1 0 0\nScan_Y=0 1 0\n", encoding="utf-8")
    return w
