/* Batch Report 지표 설명 — 화면의 ? 버튼이 여는 창의 문구를 이 파일 한 곳에서 관리한다.
   정의는 사용자 확정(2026-10-05): 시간 3칸(웨이퍼 처리 / Error · 중단 및 조치 / 유휴), 정상 · 실제 WPH, Defect 과다 중단.
   계산 예(지금 화면 숫자)는 화면이 `calc` 로 넘긴다. */
export type HelpText={t:string;what:string;f?:string[];check?:string;limits?:string[]};

const LIM_RESCAN='같은 wafer를 다시 스캔한 것도 처리 시간과 장수에 넣습니다. 투입 · 출하 정보가 없어 필요한 재스캔인지 판단할 수 없기 때문입니다(재스캔 참고 비율로 따로 보여 줌).';
const LIM_IDLE='유휴 시간은 물량 없음 · PM · 셋업 · 다운을 구분하지 못합니다(Batch Report가 없는 시간).';
const LIM_24='하루 생산능력은 24시간(4조 3교대) 쉬지 않고 돈다고 가정한 최대치입니다. 두 레시피에 같은 가정을 쓰므로 비교에는 쓸 수 있습니다.';
const LIM_CHECK='점검 스캔(S/M 0 · FOCUS 등 Lot이 아닌 스캔)은 웨이퍼 처리 시간에 넣고, 레시피 WPH 계산에서는 뺍니다.';

export const HELP:Record<string,HelpText>={
  'util.rate':{t:'가동률',what:'호기가 wafer를 처리하느라 바빴던 시간의 비율입니다.',
    f:['가동률 = 웨이퍼 처리 시간 ÷ 달력 시간','달력 시간 = 24시간 × 일수 × 호기 수'],
    check:'호기가 얼마나 바쁜지. 레시피 비교에는 쓰지 않습니다(물량에 따라 달라지므로 — 레시피는 WPH 탭에서 비교).',
    limits:[LIM_RESCAN,LIM_CHECK]},
  'util.proc':{t:'웨이퍼 처리 시간',what:'장비가 wafer를 넣고, 스캔하고, 빼던 시간입니다(로봇 이동 · 로딩 · 얼라인 포함).',
    f:['Error · 중단 없는 Batch Report → Batch Time 전체','Error · 중단이 있는 Batch Report → Pass 장수 × 1장 처리 시간 (그 Batch Report의 Batch Time을 넘지 않게)','나머지 Batch Time은 Error · 중단 및 조치 시간'],
    check:'그중 \'같은 wafer 다시 스캔\'은 이미 Pass한 wafer를 다시 스캔해 또 Pass한 몫입니다.',limits:[LIM_RESCAN,LIM_CHECK]},
  'util.loss':{t:'Error · 중단 및 조치 시간',what:'Error가 나거나 작업자가 멈춰서 결과를 내지 못한 시간과, 다시 스캔하기까지 조치한 시간입니다.',
    f:['① Error · 중단이 있는 Batch Report의 Batch Time − (Pass 장수 × 1장 처리 시간)','② 그 뒤 같은 호기에서 같은 Lot을 다시 스캔하기까지 장비가 아무것도 스캔하지 않은 시간','Error 원문별로 나눌 때: 그 Batch Report의 Error wafer 원문 비율(앞 Error 뒤 따라온 Aborted · Skipped는 앞 Error 원문)'],
    check:'작업자 중단(앞 Error 없는 Aborted.)은 Error로 세지 않지만 시간은 여기에 넣습니다 — 장비가 놀던 시간이 아니기 때문입니다. Defect 과다 중단 / 그 외 중단으로 나눠 보여 줍니다.',
    limits:['다른 Lot으로 넘어가거나 12시간 넘게 같은 Lot을 다시 스캔하지 않으면 그 사이 시간은 유휴입니다.']},
  'util.idle':{t:'유휴 시간',what:'Batch Report가 없고, Error · 중단 뒤 조치 시간도 아닌 시간입니다.',
    f:['유휴 = 달력 시간 − 웨이퍼 처리 시간 − Error · 중단 및 조치 시간'],
    check:'개선 레시피를 돌릴 수 있는 호기에 물량을 더 넣을 여유가 있는지.',limits:[LIM_IDLE]},
  'util.cal':{t:'달력 시간',what:'조사 기간 동안 호기가 쓸 수 있었던 전체 시간입니다(4조 3교대 — 하루 24시간).',
    f:['달력 시간 = 24시간 × 일수 × 호기 수'],limits:['조사 범위의 기간(모든 기간이면 처음 ~ 마지막 Batch Report 날짜) 기준입니다.']},
  'util.timetable':{t:'24시간 시간표',what:'하루를 0시 ~ 24시로 펼쳐 Batch Report 하나하나를 막대로 그립니다.',
    f:['막대 색 = 모두 Pass / Error 포함 / 작업자 중단(Defect 과다 · 그 외) / 점검 스캔','막대 아래 줄 = Error · 중단 뒤 같은 Lot을 다시 스캔하기까지 조치 대기','빈칸 = 스캔 기록 없음(유휴)'],
    check:'막대에 마우스를 올리면 자세히, 누르면 Batch Report 원문, 아래 줄을 누르면 Lot History.'},
  'wph.unit':{t:'1장 처리 시간',what:'wafer 1장을 넣고, 스캔하고, 빼기까지 걸린 시간입니다(로봇 이동 · 로딩 · 얼라인 포함).',
    f:['1장 처리 시간 = 정상 25매 Batch Report의 Batch Time 합 ÷ 장수 합','정상 25매 Batch Report = Error · 중단 없이 25매 모두 Pass한 Batch Report','호기 × 레시피마다 따로 구합니다(같은 레시피도 장비 모델마다 속도가 다를 수 있음). 그 호기에 정상 25매가 없으면 레시피 전체 값'],
    check:'Avg. Scan Time(순수 스캔)과의 차이가 로봇 이동 · 로딩 · 얼라인 몫입니다.'},
  'wph.avgscan':{t:'Avg. Scan Time',what:'Batch Report 머리말의 원문 값 그대로 — wafer 1장을 순수하게 스캔한 시간입니다(로봇 이동 · 로딩 · 얼라인 제외).',
    f:['Avg. Scan Time = 정상 25매 Batch Report의 Avg. Scan Time을 장수로 평균'],
    check:'순수 스캔 속도가 빨라졌는지. 실제 처리량 비교는 1장 처리 시간 · WPH로 합니다.'},
  'wph.normal':{t:'정상 WPH',what:'막힘없이 돌 때 한 시간에 처리하는 장수입니다.',
    f:['정상 WPH = 정상 25매 Batch Report 장수 합 × 3,600 ÷ Batch Time 합 (초)','= 3,600 ÷ 1장 처리 시간'],
    check:'레시피 속도 비교의 기준. 실제 WPH와 나란히 보면 손실 크기가 보입니다.',
    limits:['Error · 중단이 있는 Batch Report와 25매가 아닌 Batch Report는 넣지 않습니다(멈춘 시간이 섞이면 속도가 아니게 되므로).']},
  'wph.actual':{t:'실제 WPH',what:'Error · 작업자 중단으로 잃은 시간까지 포함해 실제로 낸 처리량입니다.',
    f:['실제 WPH = Pass 장수 × 3,600 ÷ (웨이퍼 처리 시간 + Error · 중단 및 조치 시간)','= Pass 장수 × 3,600 ÷ (달력 시간 − 유휴 시간) — 장비가 놀던 시간만 뺌','≈ 정상 WPH × (1 − Error · 중단 및 조치 비율)'],
    check:'정상 WPH보다 얼마나 낮은지, 그 차이가 어느 Error · 중단 때문인지(레시피 상세 › WPH 분해).',limits:[LIM_RESCAN,LIM_CHECK]},
  'wph.drop':{t:'처리량 감소',what:'정상 WPH에 비해 실제 WPH가 줄어든 비율입니다.',f:['처리량 감소 = 1 − 실제 WPH ÷ 정상 WPH'],
    check:'Error · 중단으로 잃은 몫. 레시피 상세 › WPH 분해에서 원인별로 나눠 봅니다.'},
  'wph.capacity':{t:'하루 생산능력',what:'그 호기가 그 레시피로 하루에 처리할 수 있는 최대 장수입니다.',
    f:['하루 생산능력 = 24 × 실제 WPH','레시피 합계 = 그 레시피를 돌린 호기들의 하루 생산능력 합'],
    check:'개선 레시피(PI Enhanced)를 돌릴 수 있는 호기가 적어도 합계가 기존 레시피보다 크면 개선 레시피를 쓸 수 있습니다.',
    limits:[LIM_24,'아직 그 레시피를 돌리지 않은 호기는 자료가 없어 합계에서 빠집니다.','디바이스(Job)마다 die 수가 달라 WPH가 다르므로 같은 Job 안에서 비교하세요.']},
  'wph.errrate':{t:'Error 발생률',what:'Error가 난 Batch Report의 비율입니다(wafer 수가 아니라 사건 수).',
    f:['Error 발생률 = Error 있는 Batch Report 수 ÷ 전체 Batch Report 수'],
    check:'Error가 얼마나 자주 나는지. 첫 Error 뒤 따라온 Aborted · Skipped로 부풀지 않도록 Batch Report 단위로 셉니다.',
    limits:['작업자 중단(앞 Error 없는 Aborted.)은 Error가 아니라 중단 발생률로 셉니다.']},
  'wph.stoprate':{t:'중단 발생률',what:'작업자가 멈춘 Batch Report의 비율입니다(Defect 과다 / 그 외).',
    f:['중단 발생률 = 작업자 중단 Batch Report 수 ÷ 전체 Batch Report 수'],
    check:'Defect 과다 중단이 많으면 과검출(Defect를 너무 많이 잡는) 레시피일 수 있습니다.'},
  'wph.rescan':{t:'재스캔 참고 비율',what:'이미 Pass한 wafer를 다시 스캔해 또 Pass한 장수의 비율입니다.',
    f:['재스캔 참고 비율 = 다시 스캔해 또 Pass한 장수 ÷ Pass 장수'],
    check:'이 비율이 높으면 실제 WPH가 부풀었을 수 있습니다(같은 wafer를 두 번 센 몫).',limits:[LIM_RESCAN]},
  'wph.recipe':{t:'상위 레시피 · 하위 레시피',what:'레시피 이름은 \'상위 레시피(Job) · 하위 레시피(Recipe(s))\' 입니다. 상위 레시피 하나에 하위 레시피가 여러 개 있을 수 있습니다.',
    f:['레시피 비교 = 상위 레시피마다 묶음 상자 + 들여 쓴 하위 레시피 줄','호기 × 레시피 표 = 상위 레시피 머리 줄 › 하위 레시피 합계 줄 › 호기별 줄',
      '상위 레시피 필터 = 여러 개 고르면 그 상위 레시피만 비교 · 표 · 숫자 4개 · 기간별 추이에 보임 (하나도 안 고르면 전체)'],
    check:'같은 상위 레시피 안의 하위 레시피끼리 생산능력을 비교하세요.',
    limits:['상위 레시피(디바이스)마다 die 수가 달라 WPH가 다르므로 상위 레시피끼리는 생산능력을 더하지 않습니다.']},
  'wph.period':{t:'기간별 추이 (일 · 주 · 월)',what:'정상 WPH · 실제 WPH · 하루 생산능력 · Pass 장수를 고른 기간 단위(일 · 주 · 월)마다 다시 계산해 봅니다.',
    f:['기간마다 그 기간에 시작한 Batch Report만 더해 위 숫자 4개와 같은 식으로 계산','하루 생산능력 = 호기마다 24 × 그 기간 실제 WPH 의 합 (레시피를 안 고르면 레시피 통합)',
      'Pass 장수 = 그 기간에 실제로 Pass한 장수, 하루 평균 Pass = Pass 장수 ÷ 기간 일수(조사 범위 안 날짜만)'],
    check:'레시피를 바꾼 뒤 · 호기를 손본 뒤 WPH가 오르내렸는지, 실제 생산(Pass 장수)이 생산능력에 비해 얼마나 되는지.',
    limits:['주 = ISO 주(월요일 시작, WW 번호), 월 = 달력 월. 조사 범위 끝에 걸친 주 · 월은 범위 안 날짜만 셉니다.','기간이 짧으면(일 단위) 정상 25매 Batch Report가 없어 정상 WPH가 비는 날이 많습니다.',LIM_24]},
  'wph.split':{t:'WPH 분해',what:'정상 WPH에서 실제 WPH까지 무엇 때문에 줄었는지 나눠 봅니다.',
    f:['처리 WPH = Pass 장수 × 3,600 ÷ 웨이퍼 처리 시간','기타 차이 = 정상 WPH − 처리 WPH (25매가 아닌 Lot · 느렸던 Batch Report · 다시 스캔 등)','각 손실 = 처리 WPH × 그 손실 시간 ÷ (웨이퍼 처리 + Error · 중단 및 조치)','실제 WPH = 처리 WPH − 손실 합'],
    check:'가장 긴 막대가 개선할 곳입니다.'},
  'stop.defect':{t:'Defect 과다 중단',what:'작업자가 Defect가 너무 많아 멈춘 것으로 보는 작업자 중단입니다.',
    f:['작업자 중단 = 앞에 Error 없이 Aborted.로 멈춘 Batch Report','멈출 때 wafer = 마지막 Pass wafer, 또는 스캔 도중 멈춘 wafer(Aborted. 행에 Faults가 남은 것)','멈출 때 wafer Faults > 그 레시피 정상 wafer Faults 상위 1% 값 → Defect 과다 중단, 아니면 그 외 중단'],
    check:'몇 개에서 멈출지는 작업자 재량이라 정해진 개수가 없습니다. 그래서 그 레시피에서 평소 100장 중 1장도 안 나오는 수준을 기준으로 씁니다. [기준값 · 판정 목록 보기]에서 레시피별 기준값과 이번 조사의 판정을 확인하세요.'},
  'lot.about':{t:'Lot 추적',what:'Batch Report 1장은 스캔 1번입니다. 한 Lot은 Error로 다시 스캔하거나, 나눠 스캔하거나, 다른 호기로 옮겨 스캔하면 Batch Report 여러 장에 흩어집니다. 조사 범위의 Batch Report를 Lot 단위로 다시 모아 언제 · 어느 호기에서 · 몇 번 스캔했는지, 어떤 wafer가 왜 다시 스캔됐는지, 결국 모든 wafer가 Pass했는지 보여 줍니다.',
    f:['Lot = S/M의 첫 단독 영문 3글자 + Lot ID(Wafer ID 앞 5자)','같은 호기 12시간 이내 · 같은 Recipe(s) = 이어서 스캔한 것(재스캔 · 나눠 스캔)','wafer 결과 = 한 번에 Pass / 재스캔 Pass / 중복 Pass / Pass 없음','공정 단계가 바뀌면(2D_WBG → 2D) 같은 Lot 안에서 줄을 나눠 셉니다 — 같은 wafer를 두 번 더하지 않기 위해서입니다','3D 스캔(S/M에 3D, 예 ABC-3D)은 2D와 따로 셉니다 — 서로 재스캔 · 중복 Scan이 아님','다른 호기는 48시간 이내 + 앞 스캔에 Pass하지 못한 wafer + 같은 공정 단계일 때만 이어서(호기 이동)','중복 Pass는 가장 나중 Pass를 씁니다(추천). 직접 바꾸고 저장하는 것은 개발자 기능(설정 › 정보) — 켜고 끄는 것만으로는 숫자가 바뀌지 않고 저장한 선택만 결과에 쓰입니다'],
    check:'① 지표를 누르면 해당 목록이 나옵니다. ② Lot을 누르면 새 창(Lot 창)에서 Lot History를 봅니다. ③ Pass하지 못한 Lot은 다른 호기에서 Scan되었는지 확인하세요. 자세한 판정 기준은 조사 범위 옆 [? Lot 판정 기준]에 있습니다.'},
  'lot.reasons':{t:'멈춘 이유 요약',what:'조사 범위의 Lot에서 wafer가 Pass하지 못하고 멈춘 이유를 Lot 단위로 셉니다.',
    f:['Error: wafer마다 Pass/Fail 원문의 첫 문구(앞 Error 뒤 따라온 Aborted · Skipped는 앞 Error로)','작업자 중단: 앞에 Error 없이 Aborted.로 멈춘 것 — Error가 아니라 따로 셉니다(Defect 과다 / 그 외)','재스캔하여 Pass한 Lot = 그 이유로 멈춘 wafer가 모두 나중에 Pass한 Lot'],
    check:'행을 누르면 그 이유가 있었던 Lot만 위 목록에 보입니다.'},
  'scope.logic':{t:'조사 범위',what:'고른 호기의 Reports 폴더(추가 폴더 포함)를 읽기만 합니다.',
    f:['이미 읽은 Batch Report는 다시 읽지 않기(기본 켜짐): 파일 이름 · 수정시각 · 크기가 같으면 로컬 캐시 사용, 끄면 전부 다시 엶','읽은 Batch Report를 Lot 단위로 모아 Lot 추적 · 가동률 · WPH가 같은 결과를 씁니다. 기간은 파일 이름의 스캔 날짜 기준','이미 조사한 Batch Report는 그대로 두고 폴더 목록 1번으로 새 Batch Report만 찾아 더합니다. 새 것이 없으면 지난 결과 파일(HTML · Excel)을 그대로 씁니다','한 폴더씩 순서대로 읽습니다(병렬 읽기 없음). 새 Report를 연 호기 다음에만 2초 간격(장비 접속 매너). 연결 안 되는 호기는 캐시만으로 보여 줍니다'],
    check:'화면을 다시 열면 지난 조사 결과를 로컬 캐시만으로 먼저 보여 줍니다(장비 접근 없음).'},
};
