"""빌드 전에 프로그램 버전을 한 곳에서 찍어 주는 도구(stdlib 만).

왜 필요한가 (2026-08 실사고)
-----------------------------
게시 파일명(`..._v4.0.2.exe`)과 `버전정보.json` 의 버전은 **배포 창에서 타이핑한 값**
으로 만들어지는데, 실행 중인 프로그램이 자기 버전이라고 보고하는 값은
`param_manager/__init__.py` 의 `__version__` 이다. 빌드 전에 이 값을 올리지 않으면
파일 이름만 새 버전이고 내용은 옛 버전이라, 업데이트한 뒤에도 계속
"새 버전이 있습니다"가 뜬다(실제로 그렇게 됐다).

그래서 `build_exe.bat 4.0.2` 처럼 버전을 넘기면 이 스크립트가
  1) `param_manager/__init__.py` 의 `__version__` 을 그 값으로 바꾸고
  2) PyInstaller `--version-file` 용 `build/version_info.txt` 를 만들어
     **exe 파일 속성(파일 버전)에도 같은 값**이 박히게 한다.
그 결과 배포 창이 exe 의 파일 버전을 읽어 입력값과 대조할 수 있다.

사용:
  python tools/set_version.py 4.0.2        # 버전 기록 + version_info.txt 생성
  python tools/set_version.py --show       # 현재 버전만 출력
"""

from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INIT_PY = os.path.join(ROOT, "param_manager", "__init__.py")
VERSION_INFO = os.path.join(ROOT, "build", "version_info.txt")

APP_NAME = "Camtek AOI Parameter Manager"
EXE_STEM = "Camtek_AOI_Parameter_manage"


def current_version() -> str:
    with open(INIT_PY, encoding="utf-8") as fh:
        m = re.search(r'__version__\s*=\s*"([^"]+)"', fh.read())
    return m.group(1) if m else ""


def normalize(version: str) -> str:
    """'v4.0.2' / ' 4.0.2 ' → '4.0.2'. 숫자가 없으면 예외."""
    v = re.sub(r"^[vV]+", "", str(version or "").strip())
    if not re.match(r"^\d+(\.\d+)*$", v):
        raise SystemExit(f"[ERROR] version must look like 4.0.2 (got: {version!r})")
    return v


def quad(version: str) -> tuple:
    """'4.0.2' → (4, 0, 2, 0) — Windows VERSIONINFO 는 4자리 고정."""
    nums = [int(n) for n in version.split(".")][:4]
    return tuple(nums + [0] * (4 - len(nums)))


def write_init(version: str) -> bool:
    """__init__.py 의 __version__ 을 바꾼다. 반환: 실제로 바뀌었는가."""
    with open(INIT_PY, encoding="utf-8") as fh:
        src = fh.read()
    new = re.sub(r'__version__\s*=\s*"[^"]*"', f'__version__ = "{version}"', src, count=1)
    if new == src:
        return False
    with open(INIT_PY, "w", encoding="utf-8") as fh:
        fh.write(new)
    return True


def write_version_info(version: str) -> str:
    """PyInstaller --version-file 용 VERSIONINFO 생성(문자열은 전부 ASCII)."""
    q = quad(version)
    body = f"""# Auto-generated by tools/set_version.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={q}, prodvers={q},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('FileDescription', '{APP_NAME}'),
        StringStruct('FileVersion', '{version}'),
        StringStruct('InternalName', '{EXE_STEM}'),
        StringStruct('OriginalFilename', '{EXE_STEM}_v{version}.exe'),
        StringStruct('ProductName', '{APP_NAME}'),
        StringStruct('ProductVersion', '{version}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])])
"""
    os.makedirs(os.path.dirname(VERSION_INFO), exist_ok=True)
    with open(VERSION_INFO, "w", encoding="utf-8") as fh:
        fh.write(body)
    return VERSION_INFO


def main(argv: list) -> int:
    if not argv or argv[0] in ("--show", "-s"):
        print(current_version())
        return 0
    version = normalize(argv[0])
    changed = write_init(version)
    path = write_version_info(version)
    print(f"[version] __version__ = {version}"
          + ("" if changed else "  (already set)"))
    print(f"[version] {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
